### ISSUE TITLE
Checkbox checkmark appears outside of container iOS Safari 13@

### ISSUE THREAD

**Issue by thomas-alrek** [botoxparty/XP.css#1]
See attached screenshots![image](https://user-images.githubusercontent.com/14291825/82136589-bc577100-980f-11ea-9e0f-739f611b3e00.jpeg)
![image](https://user-images.githubusercontent.com/14291825/82136594-c5484280-980f-11ea-9fb1-17fda359022e.jpeg)

**Comment by bkjoel** [comment]
Reproducible on Safari Version 13.0.5 (15608.5.11), I also grabbed a screen recording of it - 
toggling the position: absolute on the pseudo ::after positions it in the same line, what a weird behavior from Safari 🤷‍♂️

https://vimeo.com/419515875

**Comment by botoxparty** [comment]
Fix coming for this in a couple of days :)

**Comment by bkjoel** [comment]
Could you share with us what was the fix and what was Safari’s behavior?
I’m curious 🙃

**Comment by botoxparty** [comment]
@bkjoel I found that I had to explicitly set the `top` property on the `pseudo::after` for it to render correctly in Safari.

Not sure exactly what makes Safari behave like that but maybe the default of `top: auto` behaves differently in Safari to Chrome/FF

**Comment by thomas-alrek** [comment]
Seems like the range slider is also partially broken in Safari

**Comment by botoxparty** [comment]
Should be fixed in the latest release (0.2.3) :)
