### ISSUE TITLE
Scrolling horizontally causes UI elements to clash with TreeView in aside

### ISSUE THREAD

**Issue by sirocyl** [botoxparty/XP.css#19]
Seen on the docs page - don't know if it's specific to that or more of a global concern.
## Observed behavior:
When the page is wide enough to scroll horizontally - for instance, opening the "Show Code" on the [Tabs](https://botoxparty.github.io/XP.css/#tabs) view - some XP UI elements draw over the TreeView located in the aside.
## Expected behavior:
Either:
- **Easiest:** UI elements should draw underneath the TreeView in a fixed-position aside (aside z-indexes above the rest)
- **Most proper:** Aside should be free to scroll left and right, but remain fixed vertically.

This is also observed upstream, in [98.css](https://github.com/jdan/98.css) - [for example](https://user-images.githubusercontent.com/944067/85145021-f6a29c80-b219-11ea-87a7-8b43e099d5f1.png). A report [has been](https://github.com/jdan/98.css/issues/93) made there as well.

Example below:
![image](https://user-images.githubusercontent.com/944067/85144242-e8a04c00-b218-11ea-8315-9ae206aa7f2d.png)

**Comment by botoxparty** [comment]
Yep this is just a docs thing, I need to work out how i'm going to structure the docs to accommodate for other themes and will fix this then.

Thanks for reporting.
