### ISSUE TITLE
Graphical and textual glitches for <100% magnification

### ISSUE THREAD

**Issue by bmix** [botoxparty/XP.css#3]
Hello,

best to show a pic (this is with 90% zoom on Vivaldi (Chrome derivate)):

![xpcss](https://user-images.githubusercontent.com/310157/82154036-92339c80-986b-11ea-9091-6bc79260e537.png)

**Comment by botoxparty** [comment]
Thanks for reporting this! Any chance you can provide some more details about your environment? What is the resolution of the display?

**Comment by bmix** [comment]
Vivaldi | 3.0.1874.38 (Stable channel) (64-Bit)
-- | --
Revision | ca1a7297a62038cd7ef1a841248d749a0346cc41
OS | Windows 10 OS Version 1909 (Build 18363.836)
JavaScript | V8 8.1.307.32
Flash | (decativated)
User-Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.142 Safari/537.36
Command Line | "C:\Program Files (x86)\Vivaldi\Application\vivaldi.exe" --allow-file-access-from-files --flag-switches-begin --enable-gpu-rasterization --enable-zero-copy --use-angle=gl --flag-switches-end --enable-audio-service-sandbox --save-page-as-mhtml
Executable Path | C:\Program Files (x86)\Vivaldi\Application\vivaldi.exe

**Comment by botoxparty** [comment]
The font is a bitmap font and the buttons are also bitmaps, they will never really scale very well up or down.

You could try and implement them with pure CSS to fix this magnification issue.
