### ISSUE TITLE
Title bar and window controls are not sized consistently

### ISSUE THREAD

**Issue by tomrow** [botoxparty/XP.css#5]
![image](https://user-images.githubusercontent.com/10169982/82448387-8f21f180-9aa1-11ea-99ca-50538d70353c.png)

Window title bars seem thicker than Windows XP's defaults, and the window controls are not sized larger to compensate.

**Comment by botoxparty** [comment]
This should be fixed in the latest release (0.2.3) :)

Thanks for reporting
