### ISSUE TITLE
Multiple Windows

### ISSUE THREAD

**Issue by jackpurrin** [botoxparty/XP.css#62]
How do I go about creating multiple windows in the XP theme?
I would like them to be in different positions. One on the top left and the other on the botton right. Is that possible?

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added two windows with different positions (top left and bottom right) to demonstrate multiple window positioning in the XP theme. Used inline CSS to position the windows and added a section explaining how to create and position multiple windows.

You can review changes in this commit: https://github.com/mark-addams001881/botoxparty-XP.css-62/commit/399fa52828b6ca3b7293d0f3b6f3a2255260f470.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by jackpurrin** [comment]
This AI is hard to understand, right? Or is it just me?

**Comment by botoxparty** [comment]
I didn’t check that AI thing, I hope it’s not a bot.

sounds like you need to use absolute positioning on the window elements.

**Comment by jackpurrin** [comment]
Alright, thanks. Yeah, the AI is a bot.
